### ISSUE TITLE
K8s Migration: Containerize Services

### ISSUE THREAD

**Issue by GalvinGao** [penguin-statistics/backend-next#13]
## Services to containerize

- [x] `backend-next`: Website Next Backend
- [x] `frontend-v2`: Website v2 Frontend
- [x] `widget-backend`: Widget Backend
	- [x] `widget-docs`: Widget Docs
	- [x] `widget-frontend`: Widget Frontend
- [x] `planner`: Planner Backend
- [x] `probe`: Probe Service
	- [x] `prometheus`: Prometheus DB
	- [x] `grafana`: Grafana Dashboard

**Comment by GalvinGao** [comment]
`frontend-v2` is the only piece missing now. Planning to do it todayz

**Comment by FlandiaYingman** [comment]
g哦，你打算怎么containerize前端

**Comment by GalvinGao** [comment]
> g哦，你打算怎么containerize前端

Self-contained nginx/caddy seems to be the convention across implementations as they also decouples potential wanted CORS related server configurations :D

**Comment by GalvinGao** [comment]
`frontend-v2` containerization completed. closing
