### ISSUE TITLE
Unify the form of nouns in packages names

### ISSUE THREAD

**Issue by FlandiaYingman** [penguin-statistics/backend-next#2]
This project uses different forms of noun. e.g., `controllers` and `utils` are plural, but `service` is singular. I suggest renaming them all into singular form, because Golang standard library uses singular noun as its package names (e.g.: `encoding/...` instead of `encodings/...`). 

You can find more discussions at: 
- https://github.com/golang-standards/project-layout/issues/7
- https://dmitri.shuralyov.com/idiomatic-go/entries/5#comment-2

Also, I suggest following the naming guidelines [here](https://go.dev/blog/package-names) and [here](https://go.dev/doc/effective_go#names). Meaning that generic packages such as `utils` should be broken up. However I understand it's a hard work to re-organize the code, especially that this project is migrated from an existing Java backend. How do you think?

**Comment by GalvinGao** [comment]
Indeed I agree that the current project structure needs some modifications. We tried to maintain the project structure as stated in https://github.com/golang-standards/project-layout.

Unifying the usage to a singular form would be more feasible for a cleaner project layout. We'll refactor it once got time :D

Thanks a lot for the issue!

**Comment by GalvinGao** [comment]
Fixed in #38
