### ISSUE TITLE
Migrate to Go 1.18! 

### ISSUE THREAD

**Issue by FlandiaYingman** [penguin-statistics/backend-next#22]
Go 1.18 has been released 8 hours ago (https://go.dev/blog/go1.18). Migrate to use the terrific Generics and Fuzzing features and 20% Performance Improvements (says the article)!

**Comment by GalvinGao** [comment]
imo generics are not yet 100% production ready but personally I'll begin learning it. But with that says, upgrading to 1.18 is definitely a nice way to go. Fuzzing could improve some internal package's redundancy and resiliency a lot.

**Comment by FlandiaYingman** [comment]
> imo generics are not yet 100% production ready so we will second the usage of the feature itself in production. but personally I'll begin learning it. But with that says, upgrading to 1.18 is definitely a nice way to go. Fuzzing could improve some internal package's redundancy and resiliency a lot.

Absolutely agree with you! We could firstly try to use 1.18 fuzzing & generics in tests and leave production 1.17. ❤️

**Comment by GalvinGao** [comment]
fixes #22
