### ISSUE TITLE
Use "ON CONFLICT UPDATE" on matrix & trend element precalculation result update in DB

### ISSUE THREAD

**Issue by GalvinGao** [penguin-statistics/backend-next#25]
Currently this uses an auto incrementing primary key and simply, deletes all staled rows then inserts all fresh rows. It just looks nasty because the sequence will not reset on cache reset and it's just eventually gonna go wild.

Composited Primary Key or simply `ON CONFLICT UPDATE` in a transaction shall solve this easily.

**Comment by AlvISsReimu** [comment]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/25188552/172468278-3fd4687c-9fc2-4265-b98a-939a3973dc63.png">
<img width="563" alt="image" src="https://user-images.githubusercontent.com/25188552/172468304-d79e9b8a-e73e-4c32-8774-b18e8812f050.png">
<img width="569" alt="image" src="https://user-images.githubusercontent.com/25188552/172468322-58748f58-5010-4682-9ede-35ae91ca39b7.png">
<img width="565" alt="image" src="https://user-images.githubusercontent.com/25188552/172468345-d560ab1d-1244-4ca7-8e33-84746baab7fc.png">
![7D6C0A47556DD6C449F37F907265A348](https://user-images.githubusercontent.com/25188552/172468415-1190079d-eee6-46e8-9d18-ef00b401b20d.jpg)
