### ISSUE TITLE
I18N Names in Database, Intermezzi should be Intermezzo

### ISSUE THREAD

**Issue by FlandiaYingman** [penguin-statistics/backend-next#35]
In `https://penguin-stats.io/PenguinStats/api/v2/zones`. The word "intermezzi" is the plural form of "intermezzo".

**Comment by GalvinGao** [comment]
According to https://twitter.com/ArknightsEN/status/1440647069543272450/photo/1 the official UI has been labeled as `Intermezzi`. Any thoughts on why it shall be Intermezzo instead?

**Comment by FlandiaYingman** [comment]
@GalvinGao According to [Wikipedia](https://en.wikipedia.org/wiki/Intermezzo) and [the Cambridge Dictionary](https://dictionary.cambridge.org/us/dictionary/english/intermezzi), the word intermezzi (or intermezzo) in the game:

- Is borrowed from the English word "intermezzi" (or "intermezzo"), which is further borrowed from Italian word "intermezzo".
- The English word "intermezzi" is the plural form of "intermezzo"; "intermezzo" is the singular form of "intermezzi".

Assume that "Heart of Surging Flame - Side Story" means "the event 'Heart of Surging Flame' is a Side Story, then, saying "event 'Darknights Memoir' is an Intermezzi" is grammatically incorrect (saying that is like saying: "'Heart of Surging Flame' is a Side Stor**ies**").

[](https://static.wikia.nocookie.net/mrfz/images/2/24/Intermezzi.png/revision/latest?cb=20211001055838)

Arknights Fandom wiki also says:

> ### Intermezzi
>
> **Intermezzo (plural Intermezzi, which is used in-game)** events have plot points and/or elements that are tied to the Main Theme, ...
> (https://arknights.fandom.com/wiki/Event/Overview#Intermezzi)

And:

> ### Darknights Memoir
> Darknights Memoir (DM) is the fifth major [event](https://arknights.fandom.com/wiki/Event) and first **[Intermezzo](https://arknights.fandom.com/wiki/Intermezzo)** in [Arknights](https://arknights.fandom.com/wiki/Arknights).
> ...
> (https://arknights.fandom.com/wiki/Darknights_Memoir)

However, as you have said, the game **does** use the word "intermezzi" to categorize the major events. See the icon below: 

![](https://static.wikia.nocookie.net/mrfz/images/a/aa/Side_Story.png/revision/latest/scale-to-width-down/50?cb=20211001055830) ![](https://static.wikia.nocookie.net/mrfz/images/2/24/Intermezzi.png/revision/latest/scale-to-width-down/50?cb=20211001055838)

But due to the evidence mentioned above, I am pretty sure that the game somehow misused the word. If you think we should follow the game strictly, then using "Intermezzi" is okay; or you may think we could change some expression without modifying its original meaning for better reflecting the game elements (after all, it's an i18n text, not a programmatical ID!), then using 'Intermezzo' is acceptable, too. I'm just pointing out a possible problem - the choice is yours.

**Comment by GalvinGao** [comment]
Wow thanks for the effort in the first place. imo it is sensible to just stick with what the game says, and it will be a plus if we add a small annotation/tooltip to all the occurrences of the word and declare that it was wrongly translated by the devs.

**Comment by GalvinGao** [comment]
@AlvISsReimu Any add-on to this? I think me and Flandia have concluded to stay with the original in-game text. If a change on using a tooltip to note such error produced by upstream, I'll open another issue for record keeping and close this one to mark the discussion as concluded :D

**Comment by AlvISsReimu** [comment]
Remember that we have reached consensus on 3/27 in our QQ chat, that we should use 'intermezzi', even if it is a misuse of plural. I'd say we don't make change here, and use the same word with the game itself.
