### ISSUE TITLE
NATS Slow Consumer Mitigation

### ISSUE THREAD

**Issue by GalvinGao** [penguin-statistics/backend-next#49]
When NATS encountered a slow consumer it will drop the message, losing the report content. This has happened before extremely rarely but still have a huge potential to go wrong in the future, especially when we migrate to the k8s cluster

**Comment by FlandiaYingman** [comment]
In my perspective when the producer is faster than the consumer, the buffer will eventually be filled fullly and the only choice is to drop messages. Anyway, just to start a single goroutine to receive messages from NATS and put them to a channel shall solve this. Other than that, we could create a thread pool like `panjf2000/ants` and then submit consumer tasks to it. This gives the ability to dynamically adjust goroutine count.

Not quite sure whether those work. Not familiar with NATS. :D

**Comment by GalvinGao** [comment]
Yes. However the correct behavior is for NATS JetStream to store a reasonable amount of buffer when a slow-consumer is encountered, due to the fact we are not expecting those data to be temporal sequential (delivered in-order).

**Comment by GalvinGao** [comment]
wontfix: NATS will not actually drop the message due to the fact we haven't ACKed it, so NATS will send us the "dropped" message just simply later than what we'd expected.
