### ISSUE TITLE
`/PenguinStats/api/v2/recognition/defects/report/init` 可能需要改善

### ISSUE THREAD

**Issue by Tinhone** [penguin-statistics/backend-next#490]
在某些极端情况下，RecognitionResult 并非必填字段，导致无法通过网页内通道反馈截图识别缺陷

### 相关信息，部分隐去

POST | https://penguin-stats.cn/PenguinStats/api/v2/recognition/defects/report/init

状态：400 Bad Request

请求：`
{"environment":{"frontendVersion":"v3.13.7","frontendCommit":"d9005d8","recognizerVersion":"v4.6.0","recognizerOpenCVVersion":"4.5.5","recognizerAssetsVersion":"CN/23-08-25-11-36-41-12f55f","server":"CN","sessionId":"***"}}`

响应：`{"code":"INVALID_REQUEST","message":"invalid request: some or all request parameters are invalid","violations":[{"field":"InitDefectReportRequest.RecognitionResult","violation":"required","message":"RecognitionResult 为必填字段"}]}`

截图：
![图片](https://github.com/penguin-statistics/backend-next/assets/81268244/6c226b0f-35f1-4bf2-832e-14dbdad7791b)
![图片](https://github.com/penguin-statistics/backend-next/assets/81268244/4b7b5a46-971f-4264-b853-de9bd07882e4)
![图片](https://github.com/penguin-statistics/backend-next/assets/81268244/af1b92ed-3b30-403c-b32a-f223d0be3c25)

**Comment by GalvinGao** [comment]
感谢汇报，我们将尽快修复此问题

**Comment by Tinhone** [comment]
截图识别相关 issue：https://github.com/penguin-statistics/recognizer/issues/17
