### ISSUE TITLE
Typo in item name

### ISSUE THREAD

**Issue by shimeoki** [penguin-statistics/backend-next#528]
![image](https://github.com/penguin-statistics/backend-next/assets/79855381/f3c333e6-56fd-479f-8740-509093bd1731)
Should be Orirock, not Orriock. I couldn't find this item in the code (because I assume the data is in the database or backend), so I'm submitting an issue. I apologise for such a small request.

**Comment by AlvISsReimu** [comment]
Fixed, thanks!
